### PR TITLE
Use python logging class

### PR DESCRIPTION
**Pull request by schaefi**
The python logging class offers most of the functionality
we need to log our messages. However it does not provide
a progress indicator. Thus the logging class as it is used
here is also extended by a progress indicator

### CODE REVIEW

**Comment by schaefi** [comment]
be careful, when this is merged the other two open pull reques #13 and #15 will have to adapt

**Comment by bear454** [comment]
So I'll supplement for #13 after merge; and we can fight over supplementing for #15 after it's merged.

**Comment by bear454** [comment]
Rebased from master. Sorry for the noise.

**Comment by bear454** [comment]
Okay, now you're just messing with me. :dizzy_face:

**Comment by schaefi** [comment]
ah uh sorry, now it should be all set for a review

**Pull request merged**
